# -*- coding: utf-8 -*-
"""TelecomX_BR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D09hrEL1pVHAlBTpfo4QbkrmpnynQWPC

#📌 Extracão
"""

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

# 1️⃣ Carregar dados
url = "https://raw.githubusercontent.com/alura-cursos/challenge2-data-science/refs/heads/main/TelecomX_Data.json"
df = pd.read_json(url)

# Expandir colunas aninhadas
df_customer = pd.json_normalize(df["customer"])
df_phone = pd.json_normalize(df["phone"])
df_internet = pd.json_normalize(df["internet"])
df_account = pd.json_normalize(df["account"])

# Juntar tudo
df_expanded = pd.concat([
    df.drop(columns=["customer", "phone", "internet", "account"]),
    df_customer,
    df_phone,
    df_internet,
    df_account
], axis=1)

print("✅ Colunas disponíveis:", df_expanded.columns.tolist())

# Agora podemos acessar tenure, TotalCharges e Churn Reason
# Tratar dados
df_expanded.fillna({"Churn Reason": "Não informado"}, inplace=True)

df = pd.json_normalize(df.to_dict(orient="records"))

df = df.applymap(lambda x: str(x) if isinstance(x, (dict, list)) else x)

df.drop_duplicates(inplace=True)

print("✅ Dados carregados e normalizados!")

print(df.head())

print(df.info())

"""#🔧 Transformação"""

df.drop_duplicates(inplace=True)

#Agora podemos acessar tenure, TotalCharges e Churn Reason
# Tratar dados
df_expanded.fillna({"Churn Reason": "Não informado"}, inplace=True)

df_expanded["tenure"] = pd.to_numeric(df_expanded["tenure"], errors="coerce").fillna(0).astype(int)

df_expanded["Charges.Total"] = pd.to_numeric(df_expanded["Charges.Total"], errors="coerce").fillna(0)

print(df.columns.tolist())

# Padronizar nomes (minúsculo e sem espaços/pontos)
df_expanded.columns = df_expanded.columns.str.lower().str.strip().str.replace(" ", "_").str.replace(".", "_")

# 5️⃣ Tratar dados numéricos
df_expanded["charges_total"] = pd.to_numeric(df_expanded["charges_total"], errors="coerce").fillna(0)
df_expanded["tenure"] = pd.to_numeric(df_expanded["tenure"], errors="coerce").fillna(0).astype(int)

# Agora a coluna vira TotalCharges
df["account.Charges.Total"] = pd.to_numeric(df["account.Charges.Total"], errors="coerce").fillna(0)

# Garantir tipos corretos
df["account.Charges.Total"] = pd.to_numeric(df["account.Charges.Total"], errors="coerce").fillna(0)
df["customer.tenure"] = pd.to_numeric(df["customer.tenure"], errors="coerce").fillna(0).astype(int)

# Criar ticket médio
df_expanded["Ticket Médio"] = df_expanded["charges_total"] / df_expanded["tenure"]
df_expanded["Ticket Médio"] = df_expanded["Ticket Médio"].replace([float("inf"), -float("inf")], 0)



bins = [0, 6, 12, 24, 36, 48, 60, df_expanded["tenure"].max()]
labels = ["0-6m", "7-12m", "13-24m", "25-36m", "37-48m", "49-60m", "60m+"]
df_expanded["Faixa_Tempo_Cliente"] = pd.cut(df_expanded["tenure"], bins=bins, labels=labels)

"""#📊 Carga e análise"""

df_expanded = pd.concat([
    df,
    df_customer,
    df_phone,
    df_internet,
    df_account
], axis=1)

# Converter colunas para numérico antes de calcular o Ticket Médio
df_expanded["Charges.Total"] = pd.to_numeric(df_expanded["Charges.Total"], errors="coerce").fillna(0)
df_expanded["tenure"] = pd.to_numeric(df_expanded["tenure"], errors="coerce").fillna(0).astype(int)


# Criar ticket médio
df_expanded["Ticket Médio"] = df_expanded["Charges.Total"] / df_expanded["tenure"]
df_expanded["Ticket Médio"] = df_expanded["Ticket Médio"].replace([float("inf"), -float("inf")], 0)

sns.set(style="whitegrid")

# --- Taxa de churn
churn_rate = df["Churn"].value_counts(normalize=True) * 100
print("\n📊 Taxa de Churn (%):")
print(churn_rate)

# --- Gráfico 1: Churn por tipo de contrato
plt.figure(figsize=(6,4))
sns.countplot(data=df, x="account.Contract", hue="Churn", palette="Set2")
plt.title("Churn por Tipo de Contrato")
plt.show()

# --- Gráfico 2: Distribuição do tempo de cliente
plt.figure(figsize=(6,4))
sns.histplot(data=df, x="customer.tenure", hue="Churn", multiple="stack", palette="coolwarm", bins=20)
plt.title("Distribuição do Tempo de Cliente x Churn")
plt.show()

# --- Gráfico 3: Ticket médio
plt.figure(figsize=(6,4))
sns.boxplot(data=df_expanded, x="Churn", y="Ticket Médio", palette="pastel")
plt.title("Ticket Médio x Churn")
plt.show()

print(df.columns.tolist())

# Churn por tipo de contrato
if "contract" in df_expanded.columns:
    plt.figure(figsize=(6,4))
    sns.countplot(data=df_expanded, x="contract", hue="churn", palette="Set2")
    plt.title("Churn por Tipo de Contrato")
    plt.show()

# Churn por serviço de internet
if "internetservice" in df_expanded.columns:
    plt.figure(figsize=(6,4))
    sns.countplot(data=df_expanded, x="internetservice", hue="churn", palette="coolwarm")
    plt.title("Churn por Tipo de Serviço de Internet")
    plt.show()

# Distribuição do tempo de cliente x Churn
plt.figure(figsize=(6,4))
sns.histplot(data=df_expanded, x="tenure", hue="Churn", multiple="stack", bins=20, palette="pastel")
plt.title("Distribuição do Tempo de Cliente x Churn")
plt.show()

# Ticket médio x Churn
plt.figure(figsize=(6,4))
sns.boxplot(data=df_expanded, x="Churn", y="Ticket Médio", palette="muted")
plt.title("Ticket Médio x Churn")
plt.show()

"""#📄Relatorio Final

> Adicionar aspas


"""



plt.figure(figsize=(8, 5))
sns.countplot(data=df_expanded, x="account.PaymentMethod", hue="Churn", palette="pastel")
plt.title("Churn por Método de Pagamento")
plt.xlabel("Método de Pagamento")
plt.ylabel("Contagem")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print("\n💡 INSIGHTS ESTRATÉGICOS:")

print(f"- Taxa de churn total: {churn_rate['Yes']:.2f}%")

print("- Clientes com contrato mensal apresentam maior risco de evasão.")

print("- Grande parte dos cancelamentos ocorre até 12 meses de contrato.")

print("- Ticket médio mais alto está relacionado a maior chance de churn.")

print("- 'Preço mais alto' é o motivo de cancelamento mais recorrente.")

"""# **`Análise de Correlação entre Variáveis`**"""

# 1. Criar uma cópia para não afetar o original
df_corr = df_expanded.copy()

# 2. Codificar Churn como variável numérica
df_corr["Churn_num"] = df_corr["Churn"].map({"Yes": 1, "No": 0})

# 3. Selecionar apenas colunas numéricas
df_corr_numeric = df_corr.select_dtypes(include=["int64", "float64"])

# 4. Incluir a variável Churn codificada
if "Churn_num" not in df_corr_numeric.columns:
    df_corr_numeric["Churn_num"] = df_corr["Churn_num"]

# 5. Calcular correlação
correlation_matrix = df_corr_numeric.corr()

# 6. Exibir o mapa de calor
plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("📈 Matriz de Correlação entre Variáveis Numéricas")
plt.show()

"""🧠 Como interpretar:
Valores próximos de +1 indicam correlação positiva forte.

Valores próximos de -1 indicam correlação negativa forte.

Valores próximos de 0 indicam baixa ou nenhuma correlação.

Olhe principalmente a coluna Churn_num para ver quais variáveis se relacionam mais com a evasão.

```
# Isto está formatado como código
```

"""